### ISSUE TITLE
Support black's --experimental-string-processing flag

### ISSUE THREAD

**Issue by feluelle** [adamchainz/blacken-docs#185]
It would be great if blacken-docs would also allow using the `--experimental-string-processing` to split lines in the docstring if they reach the line length limit.

**Comment by adamchainz** [comment]
[Black 22.1.0](https://black.readthedocs.io/en/stable/change_log.html#id67) deprecated `--experimental-string-processing` and rolled it into `--preview`, so I've added support for passing through `--preview` in #273.

Note though that it's probably better to put the option into your configuration, like `pyproject.toml`:

```toml
[tool.black]
preview = true
```

This way the option will apply to both `black` and `blacken-docs` with no further options.
