### ISSUE TITLE
RST: Detect `::` signifying default language code-block.

### ISSUE THREAD

**Issue by carltongibson** [adamchainz/blacken-docs#195]
`blacken-docs` will do this: 

```diff
- call ``reset_queries()``, like this::
+ call ``reset_queries()``, like this:
+ 
+  .. code-block:: python
```

But it's an old-as-time RST convention that the `::` means the following code block is the default language (i.e. Python) 

Not respecting that is quite a lot of noise. Is there a way to control it? Could there be? 

Thanks! 

Refs https://github.com/django/django/pull/16261

**Comment by carltongibson** [comment]
Ah, I've missed the point there...

> ...so it could be argued that blacken-docs should be able to know about the default and lint blocks that are unmarked?

We have to add the explicit `code-block` to get the linting. 

Could the `::` be detected correctly to avoid that? 🤔

**Comment by benjaoming** [comment]
> Could the `::` be detected correctly to avoid that?

A reason to support this is quite simply to have a way for a large documentation project like Django to introduce blacken-docs without also having a huge changeset related to refactoring `::` into `.. code-block::` directives.

But I'm not sure, @carltongibson - given the already quite huge changeset if it matters much. It's just huge changeset vs. also huge changeset :smile:

**Comment by carltongibson** [comment]
It's not just the change set. It's the more verbose code style throughout the project, forever more. 😳

**Comment by benjaoming** [comment]
Working on several Sphinx projects made me unable to remember what language the default `::` will highlight, so I always use `.. code-block::`. And someone who doesn't know Sphinx by heart can probably guess what a `code-block` is, while `::` is a bit weird. So I'm pretty much :+1: on the more verbose style.

**Comment by carltongibson** [comment]
That's OK. Disagreement on such is within the bounds of reason 😜

**Comment by benjaoming** [comment]
haha, indeed, I couldn't imagine a more classic way for developers to have different experiences than this :heart: It's why there always exists `-f` and `--force` :)

**Comment by asottile** [comment]
#21 for previous discussion

**Comment by carltongibson** [comment]
Thanks for the link back @asottile 

> I don't think that's a particularly common case…

**Comment by benjaoming** [comment]
`::` could be a quirk to avoid linting but retain Python highlighting. This would be a work-around for #193 

Is this approach of interest @carltongibson - or too quirky yirky dirky? :face_with_spiral_eyes:

**Comment by carltongibson** [comment]
It's not just up to me 😄 

Personally, I **do** want to keep the `::` usage, but we can always adapt if the benefits are worth it. 

I still need to investigate all the changes but, I'm more concerned by the required _Oh, it always has to be valid code_ changes.

The trouble with skips is we no longer have an auto-formatter. 

What we need is a black-ish that will hand wave over the invalid bits. (Don't think that's on the table) 

You've been looking at this for while. I only just came to it. I also need to confer with Mariusz. 

(This seems more a discussion for the Django PR than here... 😬)

**Comment by adamchainz** [comment]
I’m not in favour of this because `::` could be any programming language.

I’ve always preferred using explicit `code-block` directives. It lets other non-Sphinx tools render the blocks correctly too, like the rST previews on GitHub.

**Comment by carltongibson** [comment]
> ...:: could be any programming language.

It **could**, but if you're using Sphinx it doesn't. Projects created by `sphinx-quickstart` use it, Django uses, CPython uses it… — it's got to be a million projects. It's a bit rich saying the whole ecosystem is wrong. 

>  It lets other non-Sphinx tools render the blocks correctly too

Sure. 👍 Hence it should clearly need a flag, like `--use-sphinx-default` say. (But names as ever.)
