### ISSUE TITLE
"--dry-run" flag

### ISSUE THREAD

**Issue by jvzammit** [adamchainz/blacken-docs#197]
Let's say I need to "blacken docs" for a large project, case in point https://github.com/django/django/pull/16261

It would be useful to separate commits into two:

1. The manual changes, to current docs, required for `blacken-docs` command to work without errors.
2. The automated changes by running `blacken-docs`.

I.e. Part of what @carltongibson suggested here https://github.com/django/django/pull/16261#issuecomment-1333341758

So this issue is about allowing the user to add a `-D` or `--dry-run` flag to the current command. This would prevent the command from changing files.

**Comment by adamchainz** [comment]
Is this really needed? You can test by undoing file changes with `git restore` afterwards. I am currently testing #196 with:

```
pre-commit run blacken-docs --all && git restore .
``

I'm concerned because “dry run” can mean a lot of things. Future users might expect it to output the changed file, or the diff. This feels a little like feature bloat when all the “undo changes”/diff/etc. functionality can be achieve with Git.

**Comment by jvzammit** [comment]
If I run `git restore .` I would lose all the changes. So for https://github.com/django/django/pull/16261 I plan to do this "cycle" progressively:

* Run `blacken-docs` command for all docs files to get what needs to change for `blacken-docs` to run
* Apply manual changes for a specific file
* Re-run

Repeat until `blacken-docs` can run without errors. Once that is reached, commit the changes done manually (first commit).

After the manual changes are committed, run `blacken-docs` and commit the changes _done by the command_ (second commit).

Full context: https://github.com/django/django/pull/16261#issuecomment-1367837571

That would make review easier for that PR. And reviewers would be able to tell whether it's a manual change or a change by blacken-docs.

I understand your concerns about the name "--dry-run". But I couldn't come up with a better name. I don't think "--fake" is a good name, for example. Any ideas?

**Comment by jvzammit** [comment]
Thanks @adamchainz ! I'll try using the flow you suggested (in the coming days).

I agree about scope creep and that "less is more".

So I'll close this issue. And ping you again in case the flow you suggested does not work.

**Comment by jvzammit** [comment]
@adamchainz I tried the flow.

In step 3:

> Manually fix a file and git add it

The only to very a file is fixed is by running `blacken-docs`, which does change the file.

Mixing my manual changes to "fix" the file with the changes by the command itself.

Need to verify the file is fixed without the command applying any changes to the file.

How to do this? That's why I did https://github.com/adamchainz/blacken-docs/pull/198

The only way I see is to apply that locally and be able to do this kind of work. But I thought it might be useful in other cases. WDYT?

**Comment by adamchainz** [comment]
I think this workflow would work? You can always add more commits with Git...

1. Write an attempted fix for a file and `git add` it.
2. Run `blacken-docs` to see if it worked.
3. `git restore .`
4. If the file is fixed, `git commit` (maybe with `--amend` to add to a previous commit of multiple fixes).
5. Loop.

**Comment by jvzammit** [comment]
Yeah it works @adamchainz thanks. It's just that it's more work. But this should be a "one time" effort with the docs that "do not pass" yet. So it's not worth bloating blacken-docs with another argument. Thanks again!
