### ISSUE TITLE
Option to extend code block types

### ISSUE THREAD

**Issue by harupy** [adamchainz/blacken-docs#214]
### Description

I love this tool! Thanks for maintaining it. In our repository ([mlflow/mlflow](https://github.com/mlflow/mlflow)), we use a custom code block `test-code-block`:

https://github.com/mlflow/mlflow/blob/8286a9a012f7e273b8eb8bb65f94b3302497b69e/mlflow/tracking/fluent.py#L81

```
    .. test-code-block:: python
        :caption: Example

        import mlflow
        # Set an experiment name, which must be unique and case-sensitive.
        experiment = mlflow.set_experiment("Social NLP Experiments")
        ...
```

As the name indicates, we test code in this block. We'd like to run `blacken-docs` on test code blocks as well.

```shell
> blacken-docs --<new-option> "test-code-block" foo.py
# Format code in both code-block and test-code-block
```

**Comment by adamchainz** [comment]
I think this would be acceptable. It would need some tweaking of the current setup as the allowed language names are currently in a global variable that gets baked into the regular expressions. That work would need deferring until after argument parsing. If you'd like to create a first PR that would be helpful - be sure to add tests, docs, and a changelog note.

**Comment by harupy** [comment]
@adamchainz Thanks for the comment! I'll file a PR.

**Comment by harupy** [comment]
@adamchainz Filed #275. Would you mind taking a look?

**Comment by harupy** [comment]
I no longer need this feature. I'm using `testcode` now.

**Comment by adamchainz** [comment]
What do you mean `testcode` ? That's not one of the existing supported block types.

**Comment by harupy** [comment]
https://github.com/adamchainz/blacken-docs/blob/c2ae49824e5ce65ef3266b002e1a9d4ef7e0b791/src/blacken_docs/__init__.py#L31

**Comment by adamchainz** [comment]
Ah right, missed those
