### ISSUE TITLE
Blacken-docs removes lines at beginning and end of codeblocks, thereby destroying the rst

### ISSUE THREAD

**Issue by jpfeuffer** [adamchainz/blacken-docs#217]
### Python Version

3.10

### Package Version

1.13

### Description

![image](https://user-images.githubusercontent.com/8102638/216025503-1278f3f2-3a8c-4a8e-b7b5-69f55ff9c131.png)

**Comment by jpfeuffer** [comment]
Probably when the first line is a comment.

**Comment by jpfeuffer** [comment]
No, it happens when the empty line between the code-block and your actual code contains the same amount of spaces as the rest of the code.
In theory, this is allowed by rst. Therefore I think Blacken-docs should handle this.

**Comment by adamchainz** [comment]
Thanks for digging into your report, I found a fix in #271.
