### ISSUE TITLE
Add support for a `--check` argument

### ISSUE THREAD

**Issue by JoaquimEsteves** [adamchainz/blacken-docs#277]
### Description

Hello, we've recently started using your tool in our team.

My issue with it is that I abhor when formatters fix my text without warning me first; this is particularly annoying with pre-commit hooks.

I'd like to request for a `--check` command that would exit with an error whenever blacken-docs would suggest a change - the original black tool offers this posibility.

If PRs are welcome I can probably cook something up.

EDIT: Created a small PR for this issue.

**Comment by simonw** [comment]
Just ran into this myself and came here to open an issue.
