### ISSUE TITLE
Not failing as `pre-commit` hook due to parsing issues

### ISSUE THREAD

**Issue by jamesbraza** [adamchainz/blacken-docs#299]
### Python Version

3.8.16

### Package Version

1.16.0

### Description

As an example, https://github.com/run-llama/llama_index/blob/v0.8.48/docs/core_modules/model_modules/llms/usage_custom.md gets an error:

```none
docs/core_modules/model_modules/llms/usage_custom.md:158: code block parse error Cannot parse: 3:4:     tokenizer_outputs_to_remove=["token_type_ids"]
```

Tracing that to the file:

```python
HuggingFaceLLM(
    ...
    tokenizer_outputs_to_remove=["token_type_ids"]
)
```

We see the error is due to forgetting a comma in the source.  This is one of many parsing errors that arise in [llama-index==0.8.48](https://github.com/run-llama/llama_index/tree/v0.8.48).

Is there some way to have `blacken-docs`'s just ignore parsing errors?  The many parsing errors hold me back from a direct adoption of `blacken-docs`.

**Comment by adamchainz** [comment]
The `--skip-errors` option ignores parsing errors.
