### ISSUE TITLE
Issue a new release please :)

### ISSUE THREAD

**Issue by jond01** [adamchainz/blacken-docs#346]
### Python Version

3.9.0

### Package Version

1.16

### Description

Hi, I would like to use some of the latest features, such as the `--check` flag, and install `blacken-docs` from the official PyPI registry.

Would you please issue a new release?
The latest one is almost a year old:
https://pypi.org/project/blacken-docs/1.16.0/#history

**Comment by adamchainz** [comment]
Thank you for the nudge. I had queued up making a release back when I merged some PRs in January, but it slipped my mind. Version 1.17.0 is out now!
